/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/b4d28d53-2a41-4cbb-a8fc-1e625cc7d308 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudIlluminance light;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Wire.h>
#include <Arduino.h>
#include <hp_BH1750.h>
int led = 7;

hp_BH1750 BH1750;
# define threshold_value 500
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(2000);
   Wire.begin();
  bool avail= BH1750.begin(BH1750_TO_GROUND);
  
  initProperties();

  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  light = BH1750.getLux();
  Serial.print(light);
  Serial.println(" lux");
  delay(1000);
  if(light > threshold_value)
  {
     Serial.println("Lights on");
     setMode(led, HIGH);
     
  }
  else{
     Serial.println("Lights off");
     setMode(led, LOW);
  
}
